drop table tb_points_interest if exists;
create table tb_points_interest (
	id bigint generated by default as identity,
	name varchar(45),
	coordinated_x number(3),
	coordinated_y number(3),
	primary key(id)
);